version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: ms_transfers_mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  transfers:
    build: .
    image: microservice-transfers:local
    container_name: ms_transfers_api
    depends_on:
      - mongo
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017
      - MONGO_DATABASE_NAME=transactions_db
      - ACCOUNTS_SERVICE_URL=http://host.docker.internal:8000
    # runs transfers app from the same image but overriding the command
    command: uvicorn src.transfers.app:create_app --factory --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"
    restart: unless-stopped
volumes:
  mongo_data: